apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # see https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  name: {{ include "lightscreen.fullname" . }}-deployment
  labels:
{{ include "lightscreen.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "lightscreen.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "lightscreen.labels" . | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{.Chart.Name}}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --certs=/etc/webhook/certs 
            - --config=/config/lightscreen.yaml
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
            
          # livenessProbe:
          #   httpGet:
          #     scheme: HTTPS
          #     port: 443
          #     path: /healthz
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "lightscreen.fullname" . }}-certs
        - name: config
          configMap:
            name: lightscreen-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
