apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightscreen.fullname" . }}
  labels:
{{ include "lightscreen.labels" . | indent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
{{ include "lightscreen.labels" . | indent 4 }}
