apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: lightscreen-webhook
  labels:
    app: lightscreen
webhooks:
  - name: lightscreen.getspectral.io
    clientConfig:
      service:
        name: lightscreen-svc
        namespace: default
        path: "/"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        lightscreen: enabled
